### PR TITLE
Visual Studio 2019 support

### PR DESCRIPTION
**Pull request by glp-ns**

### CODE REVIEW

**Comment by reduckted** [comment]
Thanks for this PR! 😁 

Have you had the _Pretty Listing_ setting turn itself off in Visual Studio 2019? I haven't been using VS 2019 a lot, but when I have been using it, I haven't noticed that setting turn off. I'd rather not update the extension unless it's actually needed in Visual Studio 2019.

**Comment by glp-ns** [comment]
I had a feeling it turning off. But I will test it further without the extension and comment back.

**Comment by alchemistmatt** [comment]
I have seen this option get unchecked behind-the-scenes in Visual Studio 2019.  I believe it only happens if I have two instances of Visual Studio 2019 open.

**Comment by alchemistmatt** [comment]
It took me a while to notice, since I primarily code in C# these days.  However, I still have a few large VB.NET projects not yet converted to C# and thus your extension is great for dealing with this ghost-in-the-machine bug.

**Comment by glp-ns** [comment]
> I have seen this option get unchecked behind-the-scenes in Visual Studio 2019. I believe it only happens if I have two instances of Visual Studio 2019 open.

I do program with multiple Visual Studios at the same time.

> I had a feeling it turning off. But I will test it further without the extension and comment back.

The pretty print got unchecked today without the extension.

**Comment by reduckted** [comment]
> The pretty print got unchecked today without the extension.

Awesome! Well, sort of. 🙃

Looks like we still need this extension. I'll publish a new version soon.

**Comment by reduckted** [comment]
I've just published v1.2 which now has support for Visual Studio 2019.

I had to make some additional changes to keep it backward-compatible with earlier versions of Visual Studio, as well as making the package load asynchronously (which will be required for all extensions in the next minor version of VS), so I wasn't able to use this PR, but thank you for the effort; It's very much appreciated. 😁

**Pull request closed without merging**
